### ISSUE TITLE
Add meta titles to the guides app

### ISSUE THREAD

**Issue by mansona** [ember-learn/guides-app#26]
@rwwagner90 I assigned this to you because you suggested it and you seemed to understand what is needed to be done 👍 

The goal of this whole project is to make things functionally **exactly** the same and worry about any more general improvements _after initial release_

To that end we need titles to match current titles, I will point out some examples that may end up being edge cases but if we get these working I will be happy shipping for the initial release.

The general structure seems to be: `Ember.js - <section title>: <page title>` where: 
- section title: is the same as the section in the TOC
- page title: is the same as the H1 at the top of the page

Examples: 
- [x] https://guides.emberjs.com/v2.17.0/routing/defining-your-routes/
	- Ember.js - Routing: Defining Your Routes
- [x] https://guides.emberjs.com/v2.17.0/
	- Ember.js - Guides and Tutorials
- [x] https://guides.emberjs.com/v2.17.0/models/
	- Ember.js - Models: Introduction

Those last 2 might be a bit tricky because they play with the index implementation, and that has already caught me a few times at this stage 😖  https://github.com/ember-learn/guides-app/issues/27

**Comment by rwwagner90** [comment]
Yep, I'm definitely down to implement this 😃

**Comment by mansona** [comment]
these use cases are now fully working 🎉 

and now the titles are working perfectly in the fastboot/prember land, thanks to @jenweber's  great work on https://github.com/ember-learn/guides-app/pull/32
