### ISSUE TITLE
Quest: Bring the new Ember based guides-app home

### ISSUE THREAD

**Issue by mansona** [ember-learn/guides-app#4]
This refactor of the guides app started as a Proof of Concept implementation of a "Just Ember" version of the Ember Guides and as a result of [discussions on the community slack](https://embercommunity.slackarchive.io/-team-learning/page-85), I would like to thank everyone in #ember-learn for their patience in answering all my questions.

The main design of this system is that all of the source markdown files are located in https://github.com/ember-learn/guides-source, which is an npm dependency of this app. Those markdown files are compiled into JSON:API using https://github.com/stonecircle/broccoli-static-site-json and the custom adapter reads the static JSON files directly.

This quest issue it to keep track of all the little things that are required to complete the app so that it is ready to replace the current https://guides.emberjs.com site. This list will likely get a lot bigger before it starts to get smaller, but **please clone the repo and test it** all the feedback we can get is much appreciated.

If any of the following tasks need more explanation please let me know and I will elaborate on a new issue for that task. You can get help on the [Ember Community Slack](https://embercommunity.slack.com/) in the #-team-learning channel if you want to help out.

# Blocker Tasks 
### Still to do
- [x] re-implement the search functionality (Issue:  https://github.com/ember-learn/guides-app/issues/6 Fixed in: https://github.com/ember-learn/guides-app/pull/39)
- [x] add hover-over `anchorable-toc` "link" for headers (Fixed in: https://github.com/ember-learn/guides-app/pull/49)
- [x] add "Old Guides" warning to older guides (Issue: #33 Fixed in: #48 ) 
### Done
- [x] ensure guides-source is up to date and each version is in sync with the current guides site
     - [x] v2.15.0 seems to be out of sync (see https://github.com/ember-learn/guides-source/pull/7)
     - [x] v2.14.0 is missing (see https://github.com/ember-learn/guides-source/pull/8)
     - [x] v2.16.0 is missing
     - [x] v2.17.0 is missing (see https://github.com/ember-learn/guides-source/pull/9)
- [x] make sure that removing the versioning ability of images doesn't cause problems for older guides (see https://github.com/ember-learn/guides-app/pull/12 and https://github.com/ember-learn/guides-source/pull/11) 
- [x] make sure there is a newline between the end of the paragraph and the  _references_ of referential style links in guides-source. This causes an issue with the markdown renderer that breaks the link. Alternatively, this could be fixed upstream: https://www.npmjs.com/package/ember-cli-showdown
- [x] fix all cases where there is a newline between ancor and link because this breaks the link e.g. `click [here]\n(https://emberjs.com` 
- [x] fix the `anchorable-toc` implementation for linking to headers throughout the guides
- [x] fix styles and display of code samples: either implement highlight in Javascript or finish the Prism configuration (see https://github.com/ember-learn/guides-app/pull/7) 
- [x] fix the indentation on /testing/acceptance for the ### Asynchronous Helpers list
- [x] make sure underscores are escaped properly so they aren't interpreted as _italics_ markdown e.g. `**node_modules / package.json**` on /tutorial/ember-cli.md
- [x] prevent `...` from being replaces with an ellipsis e.g. `...arguments` on /object-model/classes-and-instances.md
- [x] fix the chapter links for the very last page i.e. on the `/glossary/web-development` page it shouldn't say "We've Finished Glossery ... " 
- [x] get the table of contents dropdown working on mobile
- [x] upgrade the older versions (v1.10.0) `guides.yml` to follow the structure of the `pages.yml` so it will work with the new guides-app (see https://github.com/ember-learn/guides-source/pull/10)
- [x] stop hard-coding the versions and have it consumable from the guides-source - also have 'current version' defined by data from the guides-source (see https://github.com/ember-learn/guides-app/pull/9) 
- [x] implement 'current' route
- [x] make sure titles are being added as meta-data (See https://github.com/ember-learn/guides-app/issues/26) 
- [x] fix titles on "index" pages (https://github.com/ember-learn/guides-app/issues/27)

# Release Tasks
- [x] use [prember](https://github.com/ef4/prember) to pre-render

# Extra (nice to have) Tasks
- [x] remove images from guides-source because they are hosted by the app now (did this the other way round) 
- (edit un-finished tasks moved to: https://github.com/ember-learn/guides-app/projects/2)

**Comment by dopin** [comment]
👍 for using prember 😍

**Comment by jenweber** [comment]
Notes from reviewing staging at http://emberguides.stonecircle.io/v2.17.0 all the way from the top to bottom

**Blockers** (in my opinion)
- [ ] some self-referential links often don't work because they are missing versions
- [ ] `/current/` ought to be supported, causing a redirect to the latest version, i.e. `https://guides.emberjs.com/current/getting-started/quick-start/`
- [ ] header and footer ought to match currently deployed guides - I can pull Mel's changes in hacky-like. Right now it looks like css failed to load
- [ ] we need a wildcard route for 404s. Bad url brings you to a blank page. This will happen a lot after launch, no matter what we do...

**Non-blockers**
- [ ] we need a favicon
- [ ] handlebars syntax highlighting of things like `{{outlet}}`. It's totally fine as-is
- [ ] Should replace "reporting a problem" link [here](http://emberguides.stonecircle.io/v2.17.0)
- [ ] Improvements/additions to README and CONTRIBUTING.md for this repo and guides source

**Other notes**
- code block diffing in the tutorial seems fine. Can't say I note any differences.
- copy/paste without line numbers is funky. It's always been that way.
- the quickstart url [here](http://emberguides.stonecircle.io/v2.17.0/tutorial/ember-cli) doesn't work
- Chris Manson is the hero we've all been waiting for and I owe him several beers || donuts

**Comment by mansona** [comment]
This quest issue is now **only to keep track of blockers**. All nice-to-have issues related to this upgrade are being tracked on this project: https://github.com/ember-learn/guides-app/projects/2

**Comment by mansona** [comment]
All tasks that qualify for this Quest issue are now done (yay! 🎉)

We're going to be tracking any more stragglers in this Github project https://github.com/orgs/ember-learn/projects/7 mainly because a lot of the issues left to complete span multiple repos 👍 

Great job everyone! We're almost there 🎉
